---
title: &siteTitleEn The Bunker project
description: &siteDescEn Private service for web hosting, DNS, and email

timezone: Europe/Kiev
url: https://bunker.org.ua
baseurl: ""
lang: en
direction: ltr

defaults:
  - values:
      lang: en
      layout: default
  - scope:
      type: posts
    values:
      layout: post

exclude:
  - Makefile
  - README.md
  - bunker.org.ua.tar.gz

# sass:
#     style: compressed

i18n_title:
  en: *siteTitleEn
  uk: Проект «Бункер»
  ru: Проект «Бункер»

i18n_description:
  en: *siteDescEn
  uk: Приватний сервіс для веб-хостингу, DNS та електронної пошти
  ru: Частный сервис для веб-хостинга, DNS и электронной почты

i18n_lang_names:
  en: English
  uk: Українська
  ru: Русский

i18n_footer:
  en: © Dmytro K.
  uk: © Дмитро К.
  ru: © Дмитрий К.
